lime-rt/lime

doc/conf.py
doc/content.rst
doc/usermanual.rst

This branch imports the LIME user manual in the source tree. The user manual is converted to Markdown format, and is built using [Sphinx](http://sphinx-doc.org), which seems to be much mature than Mkdocs (see #27). The documentation is exported to  [Read the Docs](https://readthedocs.org).

Import documentation manual in rst format

---

src/aux.c
src/curses.c
src/lime.h
src/raytrace.c

The rearrangements (and added code) in this pull request ought not to change the output values of LIME. Their purpose is firstly to preserve code for an alternative raytracing algorithm which was first developed and present in version 1.4, and secondly to clear the ground for eventual addition of parallelization.

Raytrace rearrangements

---

Makefile
doc/usermanual.rst
lime

This PR adds options to the LIME main script.This allows to set options (verbose, no curse, fast exponential) without changing variables in the `Makefile`.

Add options to LIME main script

---

src/raytrace.c

Fixes issue #88 in which the line shape of the default model seemed to be reversed (i.e. there was a red excess instead of the expected blue one). This problem had been masked before fixing issue #38.

Fix velocity inversion bug

---

src/molinit.c

The LIME code can not handle properly the situation when there is only one collision partner and it is not H2 (see issue #86 ). If the collison partner is para- or ortho-H2 the code will not compute molecular density. The pull request fixes this problem allowing for para- or ortho-H2 to be a single collison partner.

Fix for issue #86

---

src/aux.c

This was a 1-line fix to #106. Note however that it will change the detailed values of the output image, even with DTEST set in the Makefile.

Fixes #106

---

src/aux.c
src/grid.c
src/lime.h
src/molinit.c
src/popsin.c
src/stateq.c

Implementation of the on-the-fly interpolation of collisional
coefficients that was discussed in comments to issue #81. With the
default example/model.c memory saving is about 50% and there is no
effect on speed.

On-the-fly interpolation of collision coeffs.

---

src/LTEsolution.c
src/aux.c
src/grid.c
src/lime.h
src/predefgrid.c
src/raytrace.c
src/stateq.c

The changes here are as follows:
- Added a warning if the density is too low at any grid point.
- LTE is now broken into 2 parts: the new function calculates the LTE solution for a single grid point and species.
- In stateq():
- The SVD alternative has been removed.
- The test of determinant==0 of the LU-decomposed matrix as a way to determine if the matrix is singular has been replaced by a test of the returned status value of the GSL LU solver.
- The GSL error handler has been turned off for the duration of the matrix solution iteration loop so that failure and exit can be avoided in favour of an alternative way to estimate the populations at failing grid points.
- LTE solution has been implemented as this alternative.
- A warning message has been introduced if the LU fails.

Fix for #85

---

src/aux.c
src/lime.h
src/main.c

One central element of ARTIST is a SWIG interface to LIME to allow calling LIME from Python. Since LIME is designed as a stand-alone program, integrating LIME into ARTIST so far requires changes in LIME's code, mainly in aux.c where the input parameters and images are allocated and initialized.
In this PR, the critical parts of `parseInput` and `freeInput` in aux.c are moved to the new functions `initParImg` and `freeParImg` in main.c. In addition, the `main` function is split into the functions `run` and `main` (both in main.c), where `run` can serve as an interface to LIME for external programs (such as ARTIST), and `main` is used for stand-alone LIME.
Besides this structural change, some minor changes are necessary for easy integration of LIME into ARTIST:
- Made `silent` a global …

Allows easy integration of LIME into ARTIST

---

src/aux.c
src/defaults.c
src/frees.c
src/grid.c
src/lime.h
src/main.c
src/raytrace.c
src/weights.c

Detailed changes are as follows.
- Added element `numDims` to `configInfo`.
- Changed the interface to `defaults.c:gridDensity()` as suggested in #155.
- This changed interface propagated to `weights.c:pointEvaluation()`.
- Test for the point being within the model sphere radius moved from `grid.c:buildGrid()` to `defaults.c:gridDensity()`.
- Better variable names in `grid.c:buildGrid()`.
- Removed most of the alternates for `DIM==3` in `grid.c:buildGrid()` because both `grid.x` and the new `x` are `[DIM]` in size anyway.
- Removed a few unused variables.

More generic interface to gridDensity().

---

Makefile
doc/usermanual.rst
example/model.c
src/aux.c
src/lime.h
src/main.c

This provides the necessary code to implement #63, which seems to have died of loneliness.
Note that I found my final prescription (comment of 9 Aug on the #63 thread) to be in error: the expression for `incMat` should have read
```
( c  0  s)
incMat = ( 0  1  0);
(-s  0  c)
```

New rotation

---

.gitignore
Makefile
src/raytrace.c

In the present raytracing algorithm, qhull is invoked to construct a net of Delaunay triangles from the internal grid points after these are projected onto the image plane. Well, it seems that qhull is not doing this in an error-free fashion, or at least, that it is falsely identifying some triangles as containing a given point when in fact they don't. Since it seems to be the case that the 3D triangulation by qhull requires copious sink points (i.e. on a spherical bounding surface), I conjectured that 2D triangulation would also work better with the addition of rays on a circle, the obvious candidate for which being the projection of the bounding sphere onto the image plane. This mod does seem to help, so while waiting for a better fix, this is suggested as a patch.
An alternative which …

Fix (perhaps better expressed as a workaround) for #162

---

src/LTEsolution.c
src/lime.h
src/stateq.c

`par` is defined but it is not used in the function's body.

Remove par argument from lteOnePoint

---

.gitignore
src/LTEsolution.c
src/aux.c
src/frees.c
src/grid.c
src/lime.h
src/main.c
src/messages.c
src/molinit.c
src/photon.c
src/popsin.c
src/popsout.c
src/predefgrid.c
src/raythrucells.c
src/raytrace.c
src/smooth.c
src/sourcefunc.c
src/stateq.c
src/velospline.c
src/writefits.c

There are a lot of changes in this single commit, but TBH I am about out of patience with nibbling away at major LIME issues over a space of months, having to waste time on copious amounts of repetition of the same mods and merges. I don't understand why some of you are worrying about the exactness of the results produced by this software when in my view it is at least 2 stages away from that point. We know there are problems with the algorithm; but the algorithm fixes are waiting on fixes for the code structure - the kind of thing which should have been sorted out before 1st release. First let's get the structure right, so it is not an enormous pain constantly to have to work around all the knots and peculiarities; then fix the algorithm; then by all means let's look at the numbers. The …

Untangling - starting with the dust/knu thing

---

src/aux.c
src/fastexp.c
src/frees.c
src/grid.c
src/lime.h
src/main.c
src/molinit.c
src/photon.c
src/popsin.c
src/popsout.c
src/predefgrid.c
src/raytrace.c
src/sourcefunc.c
src/velospline.c
src/writefits.c

This PR tries to fix issues #125 and #149. I had to do some rather major changes to various parts of photon.c; most importantly, I changed the whole line profile/velocity integration. 
This PR also includes some optimisations that had a small (but not insignificant) effect on running time.
There are still some things about blended lines that are not done quite correctly.

Fix #125 and #149

---

src/dims.h
src/frees.c
src/grid2fits.c
src/lime.h
src/raythrucells.c
src/raythrucells.h
src/raytrace.c

I have made the raythrucells algorithm generic (i.e. no longer hard-wired to DIM==3), and the main reason for doing this (apart from promoting those noble software goals, elegance and robustness) was to allow the same code to be used in the dims==2 situation of following image raster lines through the 2D projected cells in raytrace(), which I had hoped would address #162. However I have just this instant realized that I have shot myself in foot here because I have arranged matters such that the number of dimensions is set via a macro in the new header file dims.h. Since I have made use of structs with array members with sizes set by DIM, which I did because it saves an awful lot of mallocing, I cannot of course also use them in the same executable for dims==2. So cut-and-paste in here …

Hard-wired DIM==3 removed from ray-through-cells algorithm.

---

example/model.c
src/aux.c
src/inpars.h
src/lime.h
src/main.c
src/photon.c

This PR saves the random seeds and resets RNGs so that each iteration will have use the same set of rays. This should allow better monitoring of convergence in a yet-to-be-written PR. This PR also includes a bug fix/improvement to photon(), where the in/out split was not used quite correctly.

Partial fix to #181 and a bug fix in photon()

---

src/aux.c
src/frees.c
src/grid.c
src/inpars.h
src/lime.h
src/main.c
src/raytrace.c
src/tcpsocket.c
src/writefits.c

PR #77 did this for the inputPars. I am not sure why I did not also do the same job at that time on the user-settable image parameters, but I am doing so now.
The motivation for doing this is the same as for #77. An additional reason is that it allows easier integration of Lime into [Artist.](http://youngstars.nbi.dk/artist/Welcome.html)

Remove all but user-settable values from struct image.

---

src/aux.c
src/frees.c
src/grid.c
src/lime.h
src/main.c
src/photon.c
src/report.c
src/statistics.c

The number of rays per grid point is now set by `RAYS_PER_POINT` in lime.h, currently set to 200. The number 200 is arbitrary, but the previous `ininphot 9` resulted in roughly similar (perhaps slightly smaller) number of rays on average.
Each grid point has (already had) an individual `nphot` attribute, which is currently set to `RAYS_PER_POINT` for every non-sink grid point. Currently that is not needed, but it can be useful later when adaptive ray sampling is implemented.
Sampling of frequencies was to some extent tied to the previous 'scale the number of rays according to edges' scheme. I didn't bother trying to recreate that, because the whole frequency integration part will probably be redone soon. Instead, I'm using a very simple uniform sampling, which is more of a place holder …

Number of rays no longer scales with edges

---

src/popsout.c

This method is used to calculate the number density of radiating species
in calcGridMolDensities and it would make sense to do the same here
to return the relative abundance nmol/dens that was provided by the
user.

Calculate density as weighted sum in popsout

---

src/aux.c
src/lime.h
src/main.c
src/photon.c
src/raytrace.c

The function nextEdge() has been changed to prefer an edge which keeps the path through the model near the nominal track of the photon rather than an edge whose direction is as near as possible to the photon direction.
@tlunttil you are going to hate this because it runs 20% slower, throwing away all your nice speed gains.
I included a variant with some precalculation, which is faster, but still not as good as pre-PR.
Having written this thing I am starting to wonder how necessary it is! After all, the sampling of direction-frequency space is so sparse, perhaps it is not so important to reduce the fuzzy sampling of the model which the old algorithm implemented. This would probably only grow to importance if we implement adapative photon directions...
I also included a fix for #189.

Photon keeps near nominal track rather than to direction.

---

doc/usermanual.rst

The `gridDensity()` function has a new interface. The example on how to read input parameters is moved under the second point in the notes.

Update to gridDensity new interface in user manual

---

src/aux.c
src/grid.c
src/lime.h
src/raytrace.c
src/writefits.c

In traceray() and traceray_smooth() the subtraction of local_cmb from the ray intensities has been reinstated (it was removed from 1.6 since Tuomas and I did not understand its purpose).
This should fix #206.

Reinstates subtraction of CMB at the end of each ray trace.

---

src/aux.c
src/frees.c
src/lime.h
src/main.c
src/raythrucells.c
src/raythrucells.h
src/raytrace.c

I should make the caveat that the valgrind tool DRD still reports problems; however since these all occur outside the parallel section of raytrace.c, I don't understand what is going on. I attach the log file. Any ideas @tlunttil, or anybody else?
[dlog.txt](https://github.com/lime-rt/lime/files/713608/dlog.txt)
To generate this I did
```
cd example
../lime -n -t -p 4 model_lte.c
^c
valgrind --tool=drd --log-file=dlog.txt lime_<whatever>.x
```
BTW I was not able to squash the 'Minor' commit message via rebasing. Git seems to get confused after a merge.

Fixes the data race in raytracing (#203)

---

src/popsout.c

Although the ascii output is going to be deprecated it is still used to read the output populations. This changes the header to use whitespace delimiter for column names as in the rest of the file. The population file can then be read as CSV file by data analysis tools such as python pandas without having to specify
column names manually.

Add name of variables in header of populations file

---

src/raythrucells.c
src/raytrace.c

- In raythrucells.c:followRayThroughCells(), *chainOfCellIds and *cellExitIntcpts are now set to NULL before an exit with status==2. This fixes the seg fault.
- In raythrucells.c:followRayThroughCells() the pointers are also now freed and set to NULL if none of the calls to buildRayCellChain() returned a zero-valued status.
- In raythrucells.c:followRayThroughCells(), any kind of non-zero status will exit with *lenChainPtrs set to 0 and *entryIntcpt set to initial values.
- Redundant arguments nSteps and oneOnNSteps deleted from the raytrace.c:traceray_smooth() interface.
- In raytrace.c:raytrace(), oneOnNumActiveRaysMinus1 is now set = 1.0/(double)(numActiveRaysInternal-1) to make the raytace percentage go up to 100% again.

Fixes #212

---

src/aux.c
src/grid.c
src/main.c

At line 122 of aux.c there was a line resetting par->nSpecies artificially to 1 if the user had supplied no moldata files (thus giving a real value of zero for par->nSpecies). This ugly expedient is no longer necessary since the molData struct is no longer used to store continuum values.
The molData pointer is now also left at NULL if par->nSpecies==0.

par->nSpecies now left at 0 if no moldata files.

---

example/model.c
src/aux.c
src/defaults.c
src/frees.c
src/inpars.h
src/lime.h
src/main.c
src/writefits.c

I have removed the need for multiple raytracings when only the image unit is changed between multiple image outputs. Now the user can set a delimiter (space, comma, colon or underscore all accepted) separated string of the units required, where the unit numbers-to-type are the same as before. The unit name and file extension are then automatically appended to img[].filename.

Units-string-input

---

src/aux.c
src/frees.c
src/grid.c
src/grid2fits.c
src/grid2fits.h
src/gridio.c
src/gridio.h
src/lime.h
src/raythrucells.c
src/raytrace.c

Checks made on the presence of the five 'mandatory' functions density(), temperature(), abundance(), doppler() and velocity(), are now performed more intelligently. A test for divide-by-zero is also done on the returns of these functions and a warning issued.
This addresses #201 and replaces (or invalidates) #198. Detailed changes are as follows:
- In aux.c:parseInput() the presence of a par->gridInFile is tested, and if one has been supplied, the number of density columns is read from this and par->numDensities is set to this value.
- In grid.c:readOrBuildGrid(), all tests for the presence of mandatory functions are now (also) done before smoothing. This is so, if one is missing, the user won't have to wait until the smoothing is done before finding out.
- All tests of mandatory …

Several changes to checks of mandatory functions.

---

example/model.c
src/aux.c
src/frees.c
src/grid.c
src/inpars.h
src/lime.h
src/main.c
src/messages.c
src/molinit.c

This closes #192.
This change allows the user to use collision parameter coefficients for a non-LAMDA species without LIME printing the name of a spurious LAMDA molecule in its solution commencement message.
The value of MAX_N_COLL_PART was also increased to 20.
Removed unused argument 'partner' from collpartmesg2().
Printing of the collision partner information has been moved from readMolData() to molInit().

New optional parameter collPartNames added.

---

example/model.c
src/aux.c
src/defaults.c
src/frees.c
src/grid.c
src/grid2fits.c
src/grid2fits.h
src/inpars.h
src/lime.h
src/main.c
src/popsin.c
src/popsout.c
src/predefgrid.c

This closes #186.
Some rearrangements of struct grid and when parts of it are malloc'd have been required, as follows.
- 'abun' is no longer a pointer attribute of struct grid but a scalar attribute of struct populations.
- mallocAndSetDefaultGrid() now also takes the number of species and performs the malloc of struct grid attribute 'mol' which was previously done in main() after the call to molInit().
- popsin() no longer mallocs the grid struct, this is done beforehand via mallocAndSetDefaultGrid().
- The default abundance() function now no longer throws an exception, it returns -1 (which is a non-physical value). The absence of a user-supplied version of this function is now tested by comparing the returned value with 0. Removal of the exception was done because the user may now …

Added new semi-mandatory function molNumDensity().

---

src/grid2fits.c

In grid2fits.c: readGridExtFromFits() the grid is malloc'd initially with a call to mallocAndSetDefaultGrid()
using nSpecies=0. However, this means that (*gp).[i].mol is never malloc'd and therefore later when
abundances are read in (block starting line 1155) LIME segfaults. This is a simple fix that moves the nSpecies determination to before the mallocAndSetDefaultGrid() call and passes this as an argument so that (*gp).[i].mol is malloc'd correctly if appropriate. I don't think this breaks anything or causes any unintended behaviour.

Fix for reading in abundance values with gridInFile.

---

src/lime.h
src/stateq.c

In stateq.c the part of the matrix involving collision coefficients does not depend on the results of getjbar() and thus has been moved outside the loop now starting at line 141 (old line 45) in stateq.c. This results in a slight speedup.

Quicker stateq

---

doc/usermanual.rst
src/aux.c
src/frees.c
src/inpars.h
src/lime.h
src/main.c
src/molinit.c
src/stateq.c

Added support for providing effective IR pumping rate coefficients in an
external file `girdatfile` for each radiating species. These coefficients can
be calculated from the contribution of cascading rotational levels
within vibration bands excited by IR solar radiation as described in
the case of comets by Bensch & Bergin 2004.  This effect is relevant
for cometary coma exposed to solar radiation.

Add IR pumping read from an input file

---

example/model.c
src/raytrace.c

In traceray_smooth() the grid velocity is interpolated within the cell. This makes use of some buffer space. Previously this was being allocated at each call of the function and some unchanging indices were also calculated with each call. The buffer allocation and the unchanging calculation have now been moved outside the loop over rays.
Note that this also fixes the compiler warnings mentioned in #222.

Slight speedup of raytracing.

---

src/aux.c
src/lime.h
src/stateq.c

Some rearrangement in stateq.c to make things faster and cleaner. Also removed some old unused code.

Faster stateq

---

doc/usermanual.rst
src/aux.c
src/grid.c
src/grid2fits.c
src/gridio.c
src/inpars.h
src/lime.h
src/main.c
src/messages.c

This allows the user to run LIME with zero images specified, and thus introduces the facility to run LIME in two separate sessions (desirable for CASA integration): the first to solve the RTE and save the results to file, the second to read the file and create raytraced images from it. A new parameter `par.doSolveRTE` has been added to compensate for the loss of information when zero images are specified.

Zero images

---

.travis.yml
Makefile
Makefile.defs
doc/usermanual.rst
lime
src/aux.c
src/grid.c
src/grid2fits.c
src/grid2fits.h
src/grid2hdf5.c
src/grid2hdf5.h
src/gridio.c
src/gridio.h
src/lime.h

Previously the only file format available has been FITS. Now HDF5 can be selected. Currently this must be done by hand via commenting/uncommenting appropriate lines of gridio.h. Better would be to do it via a Makefile switch.

Adds capability to read and write grid data to HDF5.

---

src/grid.c
src/grid_aux.c
src/main.c
src/raytrace.c
src/run.c
src/writefits.c

- Numbers of grid points, radius and minScale are now read from a grid file if one is provided. The associated parameters are no longer mandatory.
- MINSCALE keyword/attribute is now written to and read from grid files.
- Global fixRandomSeeds is now set in the header of run.c, not main.c as before.
- The par->nSolveIters default has been changed to 0 to get rid of warning when LTE mode chosen.
- Function parseInput() has been rearranged a little, mostly for the sake of neatness.
- Duplicated printDone(13) call removed from write2Dfits() and write3Dfits().

Changes to make it easier to split solving from raytracing (looking ahead to the CASA interface).

---

src/solver.c

This avoids the need to transpose the colli matrix as defined in `getFixedMatrix`.

Modify colli matrix population to avoid transposing
